### ISSUE TITLE
AttributeError: 'str' object has no attribute 'encode'

### ISSUE THREAD

**Issue by Arukaito** [adafruit/Adafruit_CircuitPython_Thermal_Printer#9]
Circuit Python Version : Adafruit CircuitPython 4.0.0-alpha.5 on 2018-12-10; Adafruit Metro M0 Express with samd21g18
Thermal Printer Version : circuitpython-thermal-printer-4.x-mpy-1.1.2.zip

Im trying to run the example printer code & my code without luck

[Example](https://circuitpython.readthedocs.io/projects/thermal_printer/en/latest/examples.html)
and it returns this

```
main.py output:
Traceback (most recent call last):
  File "main.py", line 32, in <module>
  File "adafruit_thermal_printer/thermal_printer.py", line 187, in __init__
  File "adafruit_thermal_printer/thermal_printer.py", line 289, in reset
  File "adafruit_thermal_printer/thermal_printer.py", line 241, in send_command
AttributeError: 'str' object has no attribute 'encode'
```

The same error occurs with my code and the example code.
Im doing something wrong?

**Comment by caternuson** [comment]
I couldn't recreate this.

Can you try running this interactively at the REPL as shown below and post results of that.
```python
Press any key to enter the REPL. Use CTRL-D to reload.
Adafruit CircuitPython 4.0.0-alpha.5 on 2018-12-10; Adafruit Feather M4 Express with samd51j19
>>> import board
>>> import busio
>>> import adafruit_thermal_printer
>>> ThermalPrinter = adafruit_thermal_printer.get_printer_class(2.69)
>>> RX = board.RX
>>> TX = board.TX
>>> uart = busio.UART(TX, RX, baudrate=19200)
>>> printer = ThermalPrinter(uart, auto_warm_up=False)
>>> 
```

**Comment by Arukaito** [comment]
Ran in REPL 
This is the outcome in MU
Press any key to enter the REPL. Use CTRL-D to reload.
Adafruit CircuitPython 4.0.0-alpha.5 on 2018-12-10; Adafruit Metro M0 Express with samd21g18
```
>>> import board
>>> import busio
>>> import adafruit_thermal_printer
>>> ThermalPrinter = adafruit_thermal_printer.get_printer_class(2.69)
>>> RX = board.RX
>>> TX = board.TX
>>> uart = busio.UART(TX, RX, baudrate=19200)
>>> printer = ThermalPrinter(uart, auto_warm_up=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "adafruit_thermal_printer/thermal_printer.py", line 187, in __init__
  File "adafruit_thermal_printer/thermal_printer.py", line 289, in reset
  File "adafruit_thermal_printer/thermal_printer.py", line 241, in send_command
AttributeError: 'str' object has no attribute 'encode'
```

**Comment by caternuson** [comment]
Hmmm. Yep. Just verifying it's not on M0. Left out for space saving? Will let @dhalbert answer as to why and what's a good substitute.
```python
Adafruit CircuitPython 4.0.0-alpha.5 on 2018-12-10; Adafruit Feather M0 Express with samd21g18
>>> 'encode' in dir("hello")
False
```
```python
Adafruit CircuitPython 4.0.0-alpha.5 on 2018-12-10; Adafruit Feather M4 Express with samd51j19
>>> 'encode' in dir("hello")
True
>>> 
```
This *may* be a related discussion.
https://github.com/adafruit/circuitpython/issues/384
but I defer to the pros.....

**Comment by Arukaito** [comment]
Is there any workaround for `encode` with M0 ?
i really wanted to try out my recently termal printer kit, so termal printers are not compatible with M0 with this current build?
Thanks!

**Comment by Sudheertati** [comment]
Traceback (most recent call last):
  File "train_online.py", line 30, in <module>
    agent =train_agent(interpreter1)
  File "train_online.py", line 21, in train_agent
    "max_training_samples": 300
  File "/home/tringapps-admin/rasa/lib/python3.6/site-packages/rasa_core/train.py", line 173, in train_dialogue_model
    generator=endpoints.nlg,
AttributeError: 'str' object has no attribute 'nlg'

**Comment by caternuson** [comment]
Closing. `encode` is now supported in M0 boards.
```python
Adafruit CircuitPython 4.1.0 on 2019-08-02; Adafruit Metro M0 Express with samd21g18
>>> 'encode' in dir("hello")
True
>>> "hello".encode('ascii')
b'hello'
>>> 
```

**Comment by caternuson** [comment]
Oops. Except for non-Express M0's (Trinket, Gemma, etc.):
```python
Adafruit CircuitPython 4.1.0 on 2019-08-02; Adafruit Trinket M0 with samd21e18
>>> 'encode' in dir("hello")
False
```
```python
Adafruit CircuitPython 4.1.0 on 2019-08-02; Adafruit Gemma M0 with samd21e18
>>> 'encode' in dir("hello")
False 
```
Leaving closed since using a thermal printer with a non-Express board should be petty rare and generally not a recommended combo.

**Comment by ladyada** [comment]
@caternuson yep thats ok - please update the readme to let people know?

**Comment by caternuson** [comment]
okie dokie, here you go: #10

**Comment by ladyada** [comment]
huzzah
